# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8513c90c9aae39f9632e0a0e47fd97d148a7472be30d35b81253fb39128f5d4515c6784193f4d93825671f43a3606e112b604f3e5ff0fd49d261641d419a2dc1

test:
  secret_key_base: ed6eeff36f0afaaccf026bf5f1395e2515530537aa3208e6b525b6d4531ec6a432652f548e7b97c8f9b5b8bf7b11915ca308e6aed37edfb9f6e915fa4da7f922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
